---
development:
  dialect: postgres
  database: supertests
  user: supertests
  password: supertests
  host: db
  pool: 5

test:
  dialect: postgres
  database: supertests
  user: supertests
  password: supertests
  host: db
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/blog_production?sslmode=disable"}}
